/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerSearchRouteImport } from './routes/customer/search'
import { Route as CustomerMyTicketsRouteImport } from './routes/customer/my-tickets'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginVerifyRouteImport } from './routes/auth/login-verify'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CustomerPaymentTripIdRouteImport } from './routes/customer/payment.$tripId'
import { Route as CustomerBookingTripIdRouteImport } from './routes/customer/booking.$tripId'

const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerSearchRoute = CustomerSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerMyTicketsRoute = CustomerMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginVerifyRoute = AuthLoginVerifyRouteImport.update({
  id: '/auth/login-verify',
  path: '/auth/login-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPaymentTripIdRoute = CustomerPaymentTripIdRouteImport.update({
  id: '/payment/$tripId',
  path: '/payment/$tripId',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerBookingTripIdRoute = CustomerBookingTripIdRouteImport.update({
  id: '/booking/$tripId',
  path: '/booking/$tripId',
  getParentRoute: () => CustomerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-verify': typeof AuthLoginVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/my-tickets': typeof CustomerMyTicketsRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/booking/$tripId': typeof CustomerBookingTripIdRoute
  '/customer/payment/$tripId': typeof CustomerPaymentTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-verify': typeof AuthLoginVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/my-tickets': typeof CustomerMyTicketsRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/booking/$tripId': typeof CustomerBookingTripIdRoute
  '/customer/payment/$tripId': typeof CustomerPaymentTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-verify': typeof AuthLoginVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/customer/my-tickets': typeof CustomerMyTicketsRoute
  '/customer/search': typeof CustomerSearchRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/booking/$tripId': typeof CustomerBookingTripIdRoute
  '/customer/payment/$tripId': typeof CustomerPaymentTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/auth/login'
    | '/auth/login-verify'
    | '/auth/register'
    | '/customer/my-tickets'
    | '/customer/search'
    | '/customer/'
    | '/customer/booking/$tripId'
    | '/customer/payment/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/login-verify'
    | '/auth/register'
    | '/customer/my-tickets'
    | '/customer/search'
    | '/customer'
    | '/customer/booking/$tripId'
    | '/customer/payment/$tripId'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/auth/login'
    | '/auth/login-verify'
    | '/auth/register'
    | '/customer/my-tickets'
    | '/customer/search'
    | '/customer/'
    | '/customer/booking/$tripId'
    | '/customer/payment/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLoginVerifyRoute: typeof AuthLoginVerifyRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/search': {
      id: '/customer/search'
      path: '/search'
      fullPath: '/customer/search'
      preLoaderRoute: typeof CustomerSearchRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/my-tickets': {
      id: '/customer/my-tickets'
      path: '/my-tickets'
      fullPath: '/customer/my-tickets'
      preLoaderRoute: typeof CustomerMyTicketsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login-verify': {
      id: '/auth/login-verify'
      path: '/auth/login-verify'
      fullPath: '/auth/login-verify'
      preLoaderRoute: typeof AuthLoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/payment/$tripId': {
      id: '/customer/payment/$tripId'
      path: '/payment/$tripId'
      fullPath: '/customer/payment/$tripId'
      preLoaderRoute: typeof CustomerPaymentTripIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/booking/$tripId': {
      id: '/customer/booking/$tripId'
      path: '/booking/$tripId'
      fullPath: '/customer/booking/$tripId'
      preLoaderRoute: typeof CustomerBookingTripIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerMyTicketsRoute: typeof CustomerMyTicketsRoute
  CustomerSearchRoute: typeof CustomerSearchRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerBookingTripIdRoute: typeof CustomerBookingTripIdRoute
  CustomerPaymentTripIdRoute: typeof CustomerPaymentTripIdRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerMyTicketsRoute: CustomerMyTicketsRoute,
  CustomerSearchRoute: CustomerSearchRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerBookingTripIdRoute: CustomerBookingTripIdRoute,
  CustomerPaymentTripIdRoute: CustomerPaymentTripIdRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLoginVerifyRoute: AuthLoginVerifyRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
